### PR TITLE
Update Imgur trademark

### PR DESCRIPTION
**Pull request by throwaway-d**

### CODE REVIEW

**Comment by digitalblossom** [comment]
I think it might still be up to date:

https://trademarks.justia.com/878/56/n-87856490.html

**Comment by throwaway-d** [comment]
> On September 27, 2021, Imgur announced that they were acquired by MediaLab AI, Inc., a holding company of internet brands.[[7]](https://en.m.wikipedia.org/wiki/Imgur#cite_note-7)

https://en.m.wikipedia.org/wiki/Imgur

**Comment by digitalblossom** [comment]
Okay, has been merged. Thanks!

**Comment by throwaway-d** [comment]
https://help.imgur.com/hc/en-us/articles/202062878-Trademark-Use-Policy

**Pull request merged**
